version: "2"
linters:
  enable:
    - asciicheck
    - bidichk
    - bodyclose
    - errorlint
    - gosec
  settings:
    gosec:
      confidence: low
      config:
        global:
          audit: true
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
