name: "release/assets"

on:
  release:
    types: [created]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: Set Swap Space
        uses: pierotofy/set-swap-space@49819abfb41bd9b44fb781159c033dba90353a7c
        with:
          swap-size-gb: 12

      - uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5 # v5.5.0
        with:
          go-version: '1.21'
          check-latest: true

      - name: Build
        run: |
          make release-assets

      - name: Upload assets to release
        uses: svenstaro/upload-release-action@81c65b7cd4de9b2570615ce3aad67a41de5b1a13 # latest
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ./release-assets/*
          tag: ${{ github.ref }}
          overwrite: true
          file_glob: true
